I followed the instruction in line 105 and filled in for years 2000 and 2013.
I am unable to run line 122. I am getting the feedback below:

Loading required namespace: rJava
Failed with error:  ‘.onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: JAVA_HOME cannot be determined from the Registry’
Error in .rJava() : rJava cannot be loaded